<?php
// $Id$

/**
 * Impelemntation of hook_permission().
 */
function flood_control_permission() {
  return array(
    'administer flood control' => array(
      'title' => t('Administer flood control'),
      'description' => '',
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function flood_control_menu() {
  $items['admin/settings/flood-control'] = array(
    'title' => 'Flood control',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flood_control_settings_form'),
    'acccess arguments' => array('administer flood control'),
    'file' => 'flood_control.admin.inc',
  );

  return $items;
}

///**
// * Internal default variables for flood_control_var().
// */
//function flood_control_variables() {
//  return array(
//  );
//}
//
///**
// * Internal implementation of variable_get().
// */
//function flood_control_var($name, $default = NULL) {
//  static $defaults = NULL;
//
//  if (!isset($defaults)) {
//    $defaults = template_variables();
//  }
//
//  $name = 'flood_control_'. $name;
//
//  if (!isset($defaults[$name]) && !isset($default)) {
//    trigger_error(t('Default variable for %variable not found.', array('%variable' => $name)));
//  }
//
//  return variable_get($name, isset($default) || !isset($defaults[$name]) ? $default : $defaults[$name]);
//}
